// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create new account', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function getcurrentdateandtime() {
    vars["currentDate"] = await driver.executeScript("return new Date().getDate()+\"/\"+new Date().getMonth()+\"/\"+new Date().getFullYear()")
    console.log(vars["currentDate"])
    vars["currentTime"] = await driver.executeScript("return new Date().getHours()+\":\"+new Date().getMinutes()+\":\"+new Date().getSeconds()")
    console.log(vars["currentTime"])
    [object Object]
    vars["currentTime"] = await driver.executeScript("return new Date().getHours()+\":\"+new Date().getMinutes()+\":\"+new Date().getSeconds()+\"pm\"")
    [object Object]
    vars["currentTime"] = await driver.executeScript("return new Date().getHours()+\":\"+new Date().getMinutes()+\":\"+new Date().getSeconds()+\"am\"")
    [object Object]
    console.log(vars["currentTime"])
  }
  it('Logout', async function() {
    await driver.get("https://pagweb:pagwebpass@pagweb-prototype.conceptant.com//users")
    await driver.manage().window().setRect(1552, 840)
    await driver.wait(until.elementLocated(By.css(".header-avatar")), 30000)
    assert(await driver.getTitle() == "My Profile | PAG Simulated Portal")
    await driver.findElement(By.css(".header-avatar")).click()
    await driver.findElement(By.css("strong")).click()
    await driver.findElement(By.css(".adp-action-b-primary")).click()
    await driver.wait(until.elementLocated(By.css(".smart-form-header > .ng-scope")), 30000)
    assert(await driver.getTitle() == "Login | PAG Simulated Portal")
  })
  it('Create new account', async function() {
    await driver.get("https://pagweb:pagwebpass@pagweb-prototype.conceptant.com//login")
    await driver.manage().window().setRect(1552, 840)
    await driver.wait(until.elementLocated(By.xpath("//form-header[@class=\'ng-scope\']")), 150000)
    await driver.findElement(By.xpath("//a[@class=\'ng-binding\']")).click()
    assert(await driver.findElement(By.xpath("//form-header[@class=\'ng-scope\']")).getText() == "Enter Account Information")
    Getcurrentdateandtime()
    console.log(vars["currentDate"])
    console.log(vars["currentTime"])
    await driver.findElement(By.xpath("//input[@id=\'login\']")).sendKeys("ATUservars["currentDate"]${currentTime}")
    await driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys("Qwer1234!")
    await driver.findElement(By.xpath("//input[@id=\'passwordConfirmation\']")).sendKeys("Qwer1234!")
    await driver.findElement(By.css(".btn")).click()
    await driver.wait(until.elementLocated(By.css(".textoFull > span")), NaN)
    assert(await driver.findElement(By.xpath("//form-header[@class=\'ng-scope\']")).getText() == "Sign In")
    await driver.findElement(By.xpath("//input[@id=\'login\']")).sendKeys("ATUservars["currentDate"]${currentTime}")
    await driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys("Qwer1234!")
    await driver.findElement(By.css(".btn")).click()
    await driver.wait(until.elementLocated(By.xpath("//span[@id=\'logo\']")), 100000)
    assert(await driver.getTitle() == "My Profile | PAG Simulated Portal")
  })
})
