module.exports = {
  medicalConditions: {
    CHF: 'Chronic Heart Disease (CHF)',
    COPD: 'Chronic Obstructive Pulmonary Disease (COPD)',
    ESRD: 'End State Renal Disease (ESRD)',
    CVD: 'Cerebral Vascular Disease (CVD)',
    DPN: 'Depression',
    SLP: 'Sleep Disorders',
    CNR: 'Cancer',
    DLA: 'Dyslipidemia',
    OBY: 'Obesity',
    stroke: 'Stroke',
    HTx: 'Hypertension',
    ketoacidosis: 'Ketoacidosis',
    hyperosmolarity: 'Hyperosmolarity',
    renalManifestations: 'Renal Manifestations',
    hyperglycemicComa: 'Hyperglycemic Coma',
    ophthalmicManifestations: 'Ophthalmic Manifestations',
    neurologicalManifestations: 'Neurological Manifestations',
    peripheralCirculatoryDisorders: 'Peripheral Circulatory Disorders',
    hypoglycemicComa: 'Hypoglycemic Coma',
    otherSpecifiedHypoglycemia: 'Other Specified Hypoglycemia',
    hypoglycemiaUnspecified: 'Hypoglycemia, Unspecified',
    postsurgicalHypoinsulinemia: 'Postsurgical Hypoinsulinemia',
    abnormalityOfSecretionOfGlucagon: 'Abnormality of Secretion of Glucagon',
    abnormalityOfSecretionOfGastrin: 'Abnormality of Secretion of Gastrin',
    otherSpecifiedDisordersOfPancreaticInternalSecretion: 'Other Specified Disorders of Pancreatic Internal Secretion',
    unspecifiedDisorderOfPancreaticInternalSecretion: 'Unspecified Disorder of Pancreatic Internal Secretion',
  },
  diabetesMedicationTypes: {
    biguanides: 'Biguanides',
    sulfonylureas: 'Sulfonylureas',
    meglitinideDerivatives: 'Meglitinide Derivatives',
    alphaGlucosidaseInhibitors: 'Alpha-Glucosidase Inhibitors',
    thiazolidinedionesTzds: 'Thiazolidinediones (TZDs)',
    glucagonlikePeptide1Glp1Agonists: 'Glucagonlike peptide?1 (GLP-1) agonists',
    dipeptidylPeptidaseIvDpp4Inhibitors: 'Dipeptidyl peptidase IV (DPP-4) Inhibitors',
    selectiveSodiumGlucoseTransporter2Sglt2Inhibitors: 'Selective sodium-glucose transporter-2 (SGLT-2) inhibitors',
    insulins: 'Insulins',
    amylinomimetics: 'Amylinomimetics',
    bileAcidSequestrants: 'Bile acid sequestrants',
    dopamineAgonists: 'Dopamine agonists',
  },
  procedures: {
    59000: 'Amniocentesis',
    '59000-1': 'Antro-duodenal Motility Study',
    '59000-4': 'CT Scan (Computerized Tomography)',
    '59000-10': 'Insulin Pump for Diabetes',
    '59000-11': 'Lap Band (Surgery)',
    '59000-12': 'Parathyroidectomy',
    '59000-13': 'Pneumococcal Vaccination (Pneumonia Vaccine)',
    '59000-14': 'Tonometry',
    '59000-16': 'Tuberculosis Skin Test (PPD Skin Test)',
    '59000-17': 'Urinalysis',
    '59000-19': 'Cataract Surgery',
  },
  sideEffects: {
    1: 'Dizziness',
    2: 'Sweating',
    3: 'Blurred vision',
    4: 'Dry mouth',
    5: 'Palpitations',
  },
};
